[project]
name = "kitchen-to-digital"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "confluent-kafka[avro,schemaregistry]>=2.15.1",
    "fastavro>=1.12.2",
    "python-dotenv>=1.2.3",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
